
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENUP = 7;
  public static final int MULTIPLICACION = 26;
  public static final int IGUAL = 23;
  public static final int PAR_CER = 21;
  public static final int POSITIONXY = 11;
  public static final int DIVISION = 27;
  public static final int SUMA = 24;
  public static final int TEXTO_PARAM = 19;
  public static final int PAR_ABI = 20;
  public static final int TOCENTER = 9;
  public static final int COLOR = 10;
  public static final int POSITIONY = 13;
  public static final int POSITIONX = 12;
  public static final int DOS_PUNTOS = 22;
  public static final int BACKWARD = 3;
  public static final int RIGHT = 4;
  public static final int FORWARD = 2;
  public static final int COMA = 28;
  public static final int PENDOWN = 8;
  public static final int LEFT = 5;
  public static final int EOF = 0;
  public static final int DIGITO = 29;
  public static final int SHOWTURTLE = 15;
  public static final int TODRAW = 17;
  public static final int TOERASE = 16;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 30;
  public static final int HIDETURTLE = 14;
  public static final int CLEARS = 6;
  public static final int ENTERO = 33;
  public static final int COMENTARIO = 32;
  public static final int HEXADECIMAL = 31;
  public static final int REPEAT = 18;
  public static final int RESTA = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FORWARD",
  "BACKWARD",
  "RIGHT",
  "LEFT",
  "CLEARS",
  "PENUP",
  "PENDOWN",
  "TOCENTER",
  "COLOR",
  "POSITIONXY",
  "POSITIONX",
  "POSITIONY",
  "HIDETURTLE",
  "SHOWTURTLE",
  "TOERASE",
  "TODRAW",
  "REPEAT",
  "TEXTO_PARAM",
  "PAR_ABI",
  "PAR_CER",
  "DOS_PUNTOS",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "COMA",
  "DIGITO",
  "IDENTIFICADOR",
  "HEXADECIMAL",
  "COMENTARIO",
  "ENTERO"
  };
}

